branch-defaults:
  ebDeploy:
    environment: flask-tendies
    group_suffix: null
  master:
    environment: flask-tendies
environment-defaults:
  flask-env:
    branch: ebDeploy
    repository: TendiesPy
  tendies-env:
    branch: null
    repository: null
global:
  application_name: flask-tendies-py
  branch: null
  default_ec2_keyname: awsEBTendies
  default_platform: python2.7
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
